name: CatCraft
main: com.gray17.soul.catcraft.CatCraft
version: 1.17.095
description: A plugin that protects cats via deterrence. Includes other commands for a more comfortable server control.
api-version: 1.17

commands:
  catcraft:
    description: Universal command, features so far are msg, kill, inv, ender, permission, disarm. Alias = cc
    usage: type in '/catcraft(or /cc) help' for a list of available commands
    permission: CatCraft.catcraft
    permission-message: you don't have the permission to use this command
  cc:
    description: Universal command, features so far are msg, kill, inv, ender, permission, disarm.
    usage: type in '/catcraft(or /cc) help' for a list of available commands
    permission: CatCraft.catcraft
    permission-message: you don't have the permission to use this command
  ccw:
    description: Quick whisper function. Follows the following syntax - /ccw <player> <message>
    usage: type in '/catcraft(or /cc) help' for a list of available commands
    permission: CatCraft.catcraft
    permission-message: you don't have the permission to use this command

permissions:
    chat.format.*:
        